
import com.mysql.jdbc.Connection;
import java.math.BigInteger;
import java.security.SecureRandom;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Alan, David, Jack, Jinn
 */
public class AdminMenu extends javax.swing.JFrame {
    String name, type, password, id;

    Connection con = null;
    String host = "jdbc:mysql://199.195.214.108/ca314project";
    //String host = "jdbc:mysql://localhost/ca314project";
    private String adminU = "college";
    private String adminP = "collegeproject";
    //private String adminU = "root";
    //private String adminP = "root";
    
    PreparedStatement stmt = null;
    PreparedStatement check = null;
    ResultSet rs = null;
    private SecureRandom random = new SecureRandom();
    /**
     * Creates new form AdminMenu
     */
    public AdminMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        newUser = new javax.swing.JTextField();
        registerButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        confirmPassword = new javax.swing.JPasswordField();
        userPassword = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        typeBox = new javax.swing.JComboBox();
        finishedButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Administration");
        setLocation(new java.awt.Point(300, 150));
        setMinimumSize(new java.awt.Dimension(777, 532));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Login.jpg"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, -10, 800, 70);
        getContentPane().add(newUser);
        newUser.setBounds(180, 260, 170, 28);

        registerButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/RegisterButton.jpg"))); // NOI18N
        registerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerButtonActionPerformed(evt);
            }
        });
        getContentPane().add(registerButton);
        registerButton.setBounds(420, 300, 150, 50);

        jLabel4.setText("New Username (no spaces)");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(180, 240, 170, 16);

        jLabel5.setText("Enter Password");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(180, 300, 110, 16);
        getContentPane().add(confirmPassword);
        confirmPassword.setBounds(180, 380, 170, 28);
        getContentPane().add(userPassword);
        userPassword.setBounds(180, 320, 170, 28);

        jLabel6.setText("Confirm Password");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(180, 360, 120, 16);

        jLabel7.setText("Employee Type");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(420, 240, 130, 16);

        typeBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Doctor", "Nurse" }));
        getContentPane().add(typeBox);
        typeBox.setBounds(410, 260, 170, 27);

        finishedButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/FinishedButton.jpg"))); // NOI18N
        finishedButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finishedButtonActionPerformed(evt);
            }
        });
        getContentPane().add(finishedButton);
        finishedButton.setBounds(420, 370, 150, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Background.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 50, 800, 490);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void openConnect() {
        try {
            con = (Connection) DriverManager.getConnection(host, adminU, adminP);
            System.out.println("Connection Made ADMIN");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ""
                    + "The Server Is Offline, Contact Your Administrator If The Matter Persists",
                    "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    public void closeConnect() {
        try {
            con.close();
            System.out.println("Connection Closed ADMIN");
        } catch (Exception e) {}
    }
    
    public String rand() {
        return new BigInteger(130, random).toString(32);
    }
    
    private boolean checkUserName(String s){
        try {
            openConnect();

            check = con.clientPrepareStatement("select * from users where username like ? ");
            stmt.setString(1, s);
            
            stmt.executeQuery();
            rs = stmt.getResultSet();

            if (rs.next()) {
                JOptionPane.showMessageDialog(this, ""
                        + "Username already in use. Please pick a Unique username",
                        "Error", JOptionPane.ERROR_MESSAGE);
                return false;
            } 
            
            return true;

        } catch (SQLException ex) {
            Logger.getLogger(AdminMenu.class.getName()).log(Level.SEVERE, null, ex);
            return false;
        }
    }
    
    public void clear(){
        newUser.setText("");
        userPassword.setText("");
        confirmPassword.setText("");
        typeBox.setSelectedItem("Doctor");
    }
    
    public void addUser() {
        try {
            openConnect();
            name = newUser.getText();
            type = (String) typeBox.getSelectedItem();
            password = userPassword.getText();
            String tmpPass = confirmPassword.getText();

            if (password.equals(tmpPass)) {

                stmt = con.prepareStatement("INSERT INTO users VALUES (?,?,?,?)");

                stmt.setString(1, name);
                stmt.setString(2, type);
                stmt.setString(3, password);
                stmt.setString(4, rand());

                stmt.executeUpdate();

                JOptionPane.showMessageDialog(this, "Thank You The "
                        + "User: " + name + " Has Been Added With A Position " + type);
                clear();
                closeConnect();
            } else {
                JOptionPane.showMessageDialog(this, ""
                        + "Passwords Dont Match",
                        "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (SQLException ex) {
            Logger.getLogger(AdminMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void registerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerButtonActionPerformed
        addUser();
    }//GEN-LAST:event_registerButtonActionPerformed

    private void finishedButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finishedButtonActionPerformed
        setVisible(false);
        Login log = new Login();
        log.setup();
        log.setVisible(true);
    }//GEN-LAST:event_finishedButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new AdminMenu().setVisible(true);
         
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField confirmPassword;
    private javax.swing.JButton finishedButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField newUser;
    private javax.swing.JButton registerButton;
    private javax.swing.JComboBox typeBox;
    private javax.swing.JPasswordField userPassword;
    // End of variables declaration//GEN-END:variables
}
